openapi: 3.0.3
info:
  title: SmartDesk API (draft)
  version: 0.1.0
paths:
  /auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '200':
          description: OK
  /tickets:
    get:
      summary: Listar tickets
      responses:
        '200':
          description: OK
